### ISSUE TITLE
NYU Depth Dataset and Depth Estimation

### ISSUE THREAD

**Issue by maryam-mohebbi** [maryam-mohebbi/Depth-Aware-Object-Detection#3]
Implement depth estimation using the NYU Depth Dataset.
- Familiarize with and preprocess the NYU Depth Dataset for depth estimation.
- Research and implement a depth estimation technique suitable for the NYU Depth Dataset.
- Test and optimize the depth estimation model for accuracy in depth prediction.

**Comment by maryam-mohebbi** [comment]
Related links:
https://arxiv.org/abs/1406.2283#:~:text=Depth%20Map%20Prediction%20from%20a,3D%20geometry%20of%20a%20scene
https://arxiv.org/abs/1708.06500#:~:text=,from%20sparse%20laser%20scan%20data
https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

**Comment by maryam-mohebbi** [comment]
Maybe it is worth looking at this dataset:
https://www.cvlibs.net/datasets/kitti/index.php

- Right color images, if want to use stereo information (12 GB): Having both the left and right images will allow us to use stereo vision techniques to estimate depth.

**Comment by maryam-mohebbi** [comment]
for LiDAR data for depth information:

- Velodyne point clouds, if you want to use laser information (29 GB): This contains the raw LiDAR scans that provide depth information for the scenes.

**Comment by maryam-mohebbi** [comment]
We need to use one dataset for both Object detection and Depth detection.
Object detection can be any dataset, but for the depth we need outdoor dataset. So we have to limit our dataset to which one can support both goal.

**Comment by AhmedDiderRahat** [comment]
I think for depth calculation we can use https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction dataset
